name: CI — Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            python -m pip install --upgrade pip
            pip install pytest
          fi

      - name: Run tests with pytest
        run: |
          mkdir -p test-results
          pytest --maxfail=1 --disable-warnings -q --junitxml=test-results/junit.xml || true

      - name: Upload test results (junit xml)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results/

      - name: Upload log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: /home/runner/work/${{ github.repository }}/
